### PR TITLE
Allow using system-installed p4est library with MPI enabled

### LINKED ISSUE #10: Allow to substitute p4est library with system-installed library with MPI support
Once #4 and #5 are resolved, we should also allow build P4est.jl with a custom MPI-build of libp4est.

### PR DESCRIPTION
**Pull request by sloede**
Closes #10.

### CODE REVIEW

**Review by ranocha — APPROVED** [review]
Nice!

**Comment by sloede** [comment]
The README still needs to ve updated with the three new environment variables to control the build process. Then, my plan would be as follows:
* merge this and create release
* update P4est_jll to build p4est with MPI support
* update Pest.jl to use an MPI-enabled p4est by default (ie, flip the default value of JULIA_P4EDT_USES_MPI) and release v0.2.0

**Comment by ranocha** [comment]
Sounds good to me :+1:

**Comment by ranocha** [comment]
Feel free to merge this once you've updated the README.md.

**Pull request merged**
