### PR TITLE
Create Downgrade.yml

### PR DESCRIPTION
**Pull request by JoshuaLampert**
Similar to https://github.com/SciML/SciMLBase.jl/pull/553.

See https://github.com/cjdoris/julia-downgrade-compat-action and also https://github.com/trixi-framework/Trixi.jl/pull/1771.

### CODE REVIEW

**Comment by JoshuaLampert** [comment]
There is a bug in the GitHub action that fails if a package name contains an underscore (here P4est_jll), see https://github.com/cjdoris/julia-downgrade-compat-action/pull/2.

**Comment by JoshuaLampert** [comment]
The GitHub action is fixed now and in principle [it works](https://github.com/trixi-framework/P4est.jl/actions/runs/7666717285/job/20895084090) with the newest version. I've set the lower compat bounds to the lowest possible such that after downgrading the tests still pass.
However, it seems that `- uses: cjdoris/julia-downgrade-compat-action@v1` doesn't recognize the newest version v1.0.7 of the GitHub action although it's [already released](https://github.com/marketplace/actions/downgrade-julia-compat-entries?version=v1.0.7). Explicitly stating `- uses: cjdoris/julia-downgrade-compat-action@v1.0.7` fixes the version, but I'd rather not like to specify the exact version. Usually, `@v1` should take the latest release, shouldn't it @ranocha?

**Comment by ranocha** [comment]
Looks like GitHub is doing weird stuff here, see https://devopsjournal.io/blog/2022/10/19/How-GitHub-Actions-versioning-works

The `@vXYZ` specification makes it look at a tag `vXYZ` in the repo. The tag `v1` in the repo points to an old version, see https://github.com/cjdoris/julia-downgrade-compat-action/tags 
The maintainer has to update the tag manually to make it work as you (and I) would expect. Thus, it's fine to use `julia-downgrade-compat-action@v1.0.7` explicitly.

**Comment by JoshuaLampert** [comment]
Ok, I set the version back to v1.0.7.

**Review by ranocha — APPROVED** [review]
Thanks!

**Pull request merged**
