### PR TITLE
Localize functions inside @testsets 

### PR DESCRIPTION
**Pull request by JoshuaLampert**
This should tick off the second point of #54. According to [this comment](https://github.com/JuliaLang/julia/issues/23878#issuecomment-413604675) adding a `$` in front of the functions inside `@cfunction` lets you localize the function definition inside the `@testset`.

### CODE REVIEW

**Review by ranocha — CHANGES_REQUESTED** [review]
> adding a `$` in front of the functions inside `@cfunction` lets you localize the function definition inside the `@testset`

According to the docs at https://docs.julialang.org/en/v1/base/c/#Base.@cfunction, this doesn't work on all architectures - in particular on ARM (which is used by the latest macs). Do we have another alternative?

**Comment by JoshuaLampert** [comment]
Ok, I look for another alternative.

**Comment by JoshuaLampert** [comment]
I put the `@testset`s containg `@cfunction`s in separate files as you also suggested @ranocha.

**Review by ranocha — APPROVED** [review]
Thanks!

**Pull request merged**
